//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All backup jobs completed..
        /// </summary>
        internal static string allJobsCompleted {
            get {
                return ResourceManager.GetString("allJobsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EasySave Backup Software.
        /// </summary>
        internal static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language (en/fr):.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to exit? (y/n).
        /// </summary>
        internal static string confirmExit {
            get {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory not found!.
        /// </summary>
        internal static string dirNotFound {
            get {
                return ResourceManager.GetString("dirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid job number..
        /// </summary>
        internal static string invalidJobNumber {
            get {
                return ResourceManager.GetString("invalidJobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid option, please try again..
        /// </summary>
        internal static string invalidOption {
            get {
                return ResourceManager.GetString("invalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job completed successfully..
        /// </summary>
        internal static string jobCompleted {
            get {
                return ResourceManager.GetString("jobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job created successfully..
        /// </summary>
        internal static string jobCreated {
            get {
                return ResourceManager.GetString("jobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error creating backup job..
        /// </summary>
        internal static string jobCreateError {
            get {
                return ResourceManager.GetString("jobCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job failed..
        /// </summary>
        internal static string jobFailed {
            get {
                return ResourceManager.GetString("jobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        internal static string jobPaused {
            get {
                return ResourceManager.GetString("jobPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup job started....
        /// </summary>
        internal static string jobStarted {
            get {
                return ResourceManager.GetString("jobStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string jobStopped {
            get {
                return ResourceManager.GetString("jobStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string jobStopped1 {
            get {
                return ResourceManager.GetString("jobStopped1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language changed successfully..
        /// </summary>
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Job.
        /// </summary>
        internal static string menuCreateJob {
            get {
                return ResourceManager.GetString("menuCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List backup jobs.
        /// </summary>
        internal static string menuListJobs {
            get {
                return ResourceManager.GetString("menuListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove .
        /// </summary>
        internal static string menuRemoveJob {
            get {
                return ResourceManager.GetString("menuRemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run all .
        /// </summary>
        internal static string menuRunAllJobs {
            get {
                return ResourceManager.GetString("menuRunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run Job.
        /// </summary>
        internal static string menuRunJob {
            get {
                return ResourceManager.GetString("menuRunJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup jobs found..
        /// </summary>
        internal static string noJobs {
            get {
                return ResourceManager.GetString("noJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        internal static string pauseJob {
            get {
                return ResourceManager.GetString("pauseJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume.
        /// </summary>
        internal static string pressAnyKey {
            get {
                return ResourceManager.GetString("pressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select backup type (1 for Full, 2 for Differential):.
        /// </summary>
        internal static string promptBackupType {
            get {
                return ResourceManager.GetString("promptBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter job name:.
        /// </summary>
        internal static string promptJobName {
            get {
                return ResourceManager.GetString("promptJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter source directory:.
        /// </summary>
        internal static string promptSourceDir {
            get {
                return ResourceManager.GetString("promptSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter target directory:.
        /// </summary>
        internal static string promptTargetDir {
            get {
                return ResourceManager.GetString("promptTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a job by number:.
        /// </summary>
        internal static string selectJob {
            get {
                return ResourceManager.GetString("selectJob", resourceCulture);
            }
        }
    }
}
