//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Save.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy_Save.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All backup jobs completed..
        /// </summary>
        internal static string allJobsCompleted {
            get {
                return ResourceManager.GetString("allJobsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasySave Backup Software.
        /// </summary>
        internal static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language (en/fr):.
        /// </summary>
        internal static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit? (y/n).
        /// </summary>
        internal static string confirmExit {
            get {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found!.
        /// </summary>
        internal static string dirNotFound {
            get {
                return ResourceManager.GetString("dirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid job number..
        /// </summary>
        internal static string invalidJobNumber {
            get {
                return ResourceManager.GetString("invalidJobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option, please try again..
        /// </summary>
        internal static string invalidOption {
            get {
                return ResourceManager.GetString("invalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job completed successfully..
        /// </summary>
        internal static string jobCompleted {
            get {
                return ResourceManager.GetString("jobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job created successfully..
        /// </summary>
        internal static string jobCreated {
            get {
                return ResourceManager.GetString("jobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating backup job..
        /// </summary>
        internal static string jobCreateError {
            get {
                return ResourceManager.GetString("jobCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job failed..
        /// </summary>
        internal static string jobFailed {
            get {
                return ResourceManager.GetString("jobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job paused. Press any key to resume....
        /// </summary>
        internal static string jobPaused {
            get {
                return ResourceManager.GetString("jobPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup job started....
        /// </summary>
        internal static string jobStarted {
            get {
                return ResourceManager.GetString("jobStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job stopped..
        /// </summary>
        internal static string jobStopped {
            get {
                return ResourceManager.GetString("jobStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed successfully..
        /// </summary>
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new backup job.
        /// </summary>
        internal static string menuCreateJob {
            get {
                return ResourceManager.GetString("menuCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List backup jobs.
        /// </summary>
        internal static string menuListJobs {
            get {
                return ResourceManager.GetString("menuListJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a backup job.
        /// </summary>
        internal static string menuRemoveJob {
            get {
                return ResourceManager.GetString("menuRemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all backup jobs.
        /// </summary>
        internal static string menuRunAllJobs {
            get {
                return ResourceManager.GetString("menuRunAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a backup job.
        /// </summary>
        internal static string menuRunJob {
            get {
                return ResourceManager.GetString("menuRunJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup jobs found..
        /// </summary>
        internal static string noJobs {
            get {
                return ResourceManager.GetString("noJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;P&apos; to pause, &apos;S&apos; to stop, or any other key to continue....
        /// </summary>
        internal static string pauseJob {
            get {
                return ResourceManager.GetString("pauseJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string pressAnyKey {
            get {
                return ResourceManager.GetString("pressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select backup type (1 for Full, 2 for Differential):.
        /// </summary>
        internal static string promptBackupType {
            get {
                return ResourceManager.GetString("promptBackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter job name:.
        /// </summary>
        internal static string promptJobName {
            get {
                return ResourceManager.GetString("promptJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter source directory:.
        /// </summary>
        internal static string promptSourceDir {
            get {
                return ResourceManager.GetString("promptSourceDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter target directory:.
        /// </summary>
        internal static string promptTargetDir {
            get {
                return ResourceManager.GetString("promptTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a job by number:.
        /// </summary>
        internal static string selectJob {
            get {
                return ResourceManager.GetString("selectJob", resourceCulture);
            }
        }
    }
}
