//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Resources
{
    using System;


    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy_Save.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }


        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        internal static string allJobsCompleted
        {
            get
            {
                return ResourceManager.GetString("allJobsCompleted", resourceCulture);
            }
        }


        internal static string appTitle
        {
            get
            {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }

        internal static string changeLanguage
        {
            get
            {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }


        internal static string confirmExit
        {
            get
            {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }


        internal static string dirNotFound
        {
            get
            {
                return ResourceManager.GetString("dirNotFound", resourceCulture);
            }
        }



        internal static string invalidJobNumber
        {
            get
            {
                return ResourceManager.GetString("invalidJobNumber", resourceCulture);
            }
        }


        internal static string invalidOption
        {
            get
            {
                return ResourceManager.GetString("invalidOption", resourceCulture);
            }
        }


        internal static string jobCompleted
        {
            get
            {
                return ResourceManager.GetString("jobCompleted", resourceCulture);
            }
        }


        internal static string jobCreated
        {
            get
            {
                return ResourceManager.GetString("jobCreated", resourceCulture);
            }
        }


        internal static string jobCreateError
        {
            get
            {
                return ResourceManager.GetString("jobCreateError", resourceCulture);
            }
        }


        internal static string jobFailed
        {
            get
            {
                return ResourceManager.GetString("jobFailed", resourceCulture);
            }
        }


        internal static string jobPaused
        {
            get
            {
                return ResourceManager.GetString("jobPaused", resourceCulture);
            }
        }


        internal static string jobStarted
        {
            get
            {
                return ResourceManager.GetString("jobStarted", resourceCulture);
            }
        }


        internal static string jobStopped
        {
            get
            {
                return ResourceManager.GetString("jobStopped", resourceCulture);
            }
        }


        internal static string languageChanged
        {
            get
            {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }

        internal static string menuCreateJob
        {
            get
            {
                return ResourceManager.GetString("menuCreateJob", resourceCulture);
            }
        }

        internal static string menuExit
        {
            get
            {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }


        internal static string menuListJobs
        {
            get
            {
                return ResourceManager.GetString("menuListJobs", resourceCulture);
            }
        }


        internal static string menuRemoveJob
        {
            get
            {
                return ResourceManager.GetString("menuRemoveJob", resourceCulture);
            }
        }


        internal static string menuRunAllJobs
        {
            get
            {
                return ResourceManager.GetString("menuRunAllJobs", resourceCulture);
            }
        }


        internal static string menuRunJob
        {
            get
            {
                return ResourceManager.GetString("menuRunJob", resourceCulture);
            }
        }


        internal static string menuSettings
        {
            get
            {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }


        internal static string noJobs
        {
            get
            {
                return ResourceManager.GetString("noJobs", resourceCulture);
            }
        }


        internal static string pauseJob
        {
            get
            {
                return ResourceManager.GetString("pauseJob", resourceCulture);
            }
        }


        internal static string pressAnyKey
        {
            get
            {
                return ResourceManager.GetString("pressAnyKey", resourceCulture);
            }
        }


        internal static string promptBackupType
        {
            get
            {
                return ResourceManager.GetString("promptBackupType", resourceCulture);
            }
        }


        internal static string promptJobName
        {
            get
            {
                return ResourceManager.GetString("promptJobName", resourceCulture);
            }
        }


        internal static string promptSourceDir
        {
            get
            {
                return ResourceManager.GetString("promptSourceDir", resourceCulture);
            }
        }


        internal static string promptTargetDir
        {
            get
            {
                return ResourceManager.GetString("promptTargetDir", resourceCulture);
            }
        }


        internal static string selectJob
        {
            get
            {
                return ResourceManager.GetString("selectJob", resourceCulture);
            }
        }
    }
}